export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_POSTS_SUCCESS="GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL="GET_POSTS_FAIL";

export const GET_CONTACT_SUCCESS="GET_CONTACT_SUCCESS"
export const GET_CONTACT_FAIL="GET_CONTACT_FAIL"

